apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.config.backend.name }}
  labels:
    app: {{ .Values.config.backend.name }}
spec:
  selector:
    app: {{ .Values.config.backend.name }}
  ports:
    - port: {{ .Values.config.backend.servicePort }}
      targetPort: {{ .Values.config.backend.containerPort }}
      protocol: TCP
