apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.config.backend.name }}-secret
  labels:
    app: {{ .Values.config.backend.name }}
type: Opaque
data:
  DB_PASSWORD: {{ default "" .Values.config.backend.env.database.password | b64enc | quote }}
  JWT_SECRET_KEY: {{ default "" .Values.config.backend.env.jwtSecret | b64enc | quote }}
