apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-credentials" .Values.config.serviceName }}
type: Opaque
data:
  POSTGRES_DB: {{ .Values.config.credentials.database | b64enc | quote }}
  POSTGRES_USER: {{ .Values.config.credentials.username | b64enc | quote }}
  POSTGRES_PASSWORD: {{ .Values.config.credentials.password | b64enc | quote }}
